### ISSUE TITLE
Looks interesting!

### ISSUE THREAD

**Issue by fullofcaffeine** [Elebeta/vijka#4]
Hey Jonas, greetings!

This looks interesting. I've been working with Gis a lot lately (namely PostGis, mapnik and leaflet.js/google maps) in an app I'm developing. I'll soon need to do some predictive analysis based off data I'm working on (mostly real state listings) and this tool called my attention. Not directly what I need, but I could certainly learn a few tricks from it.

I'm wondering though, why did you have to use a custom version of the Haxe compiler and the mcli? Have you tried to submit PRs for those changes?

Cheers,

-- Marcelo.

**Comment by jonasmalacofilho** [comment]
Thanks! Although, to be honest, I haven't worked enough on this for a while, and there are quite a few things I would like to improve outside the main demand assignment routines. Specifically, I would like to change the text interface to something closer to a scripting language + a REPL (yeah, probably hscript or some other Haxe subset) and to integrate Vijka with GIS softwares for two-way network visualization, inspection and edition.

Hey, I would love to hear more about this analysis you need to do, if you can share some details. You can reach me privately at `jonas at elebeta.com.br`.

Regarding the dependencies, the Readme needs some updating. Vijka should run on current versions of Haxe and mcli, or at the least on some recent upstream git tree. I'll check this during the week and update the Readme...
